default: cpsc2150/extendedTicTacToe/
	javac cpsc2150/extendedTicTacToe/BoardPosition.java cpsc2150/extendedTicTacToe/GameBoard.java cpsc2150/extendedTicTacToe/GameScreen.java

run: cpsc2150/extendedTicTacToe/
	java cpsc2150.extendedTicTacToe.GameScreen

clean: cpsc2150/extendedTicTacToe/
    rm -f cpsc2150/extendedTicTacToe/*.class

