default: cpsc2150/listDec/IShuffleList.java cpsc2150/listDec/ShuffleApp.java cpsc2150/listDec/ShuffleList.java
		javac -Xlint cpsc2150/listDec/ShuffleApp.java

run: cpsc2150/listDec/ShuffleApp.class
		java cpsc2150.listDec.ShuffleApp

clean:
		rm -f cpsc2150/listDec/*.class
