default: cpsc2150/MyQueue/
	javac cpsc2150/MyQueue/ArrayQueue.java cpsc2150/MyQueue/ListQueue.java cpsc2150/MyQueue/QueueApp.java cpsc2150/MyQueue/IQueue.java cpsc2150/MyQueue/AbsQueue.java

run: cpsc2150/MyQueue/QueueApp.class
	java cpsc2150.MyQueue.QueueApp

clean:
	rm -f *.class
