default: cpsc2150/MyQueue/
	javac cpsc2150/MyQueue/ArrayQueue.java cpsc2150/MyQueue/ListQueue.java cpsc2150/MyQueue/QueueApp.java cpsc2150/MyQueue/IQueue.java cpsc2150/MyQueue/AbsQueue.java cpsc2150/MyQueue/StringQueueApp.java

runInt: cpsc2150/MyQueue/QueueApp.class
	java cpsc2150.MyQueue.QueueApp

runString: cpsc2150/MyQueue/StringQueueApp.class
	java cpsc2150.MyQueue.StringQueueApp

clean:
	rm -f *.class